### ISSUE TITLE
Mobs switching sides.

### ISSUE THREAD

**Issue by beb4x** [starfield9/Monster-Industries#1]
**Describe the bug**
Using the Dirty Tactic to switch mobs to enemy side will teleport enemies slaves into their hopper and stop paper production. You are also unable to repurchase those slaves as the buttons are gone. 
Additionally, this tactic says that it doesn't affect the Wither, but twice now the Wither was sent, but then could not be sent back afterwards.

**To Reproduce**
Activate the dirty tactic to switch mobs to enemy side.

**Minecraft Version:** 
1.13.2

**Comment by burturt** [comment]
Fixed in https://github.com/burturt/Monster-Industries/releases/tag/4.0.0-beta.2. Thanks for reporting!
