### ISSUE TITLE
Leftover items from previous game.

### ISSUE THREAD

**Issue by beb4x** [starfield9/Monster-Industries#2]
**Describe the bug**
Placed Wither Skeleton Skulls that did not activate a Wither will drop to the floor and are able to be picked up and used in the next match.

**To Reproduce**
1. Place Wither Skulls on soul sand, or likely anywhere else (unconfirmed)
2. Leave Skulls there until round ends.
3. Start a new game
4. Skulls will be on the ground to be picked up

**Expected behavior**
I would expect item entities to be cleared at the start of a round.

**Minecraft Version:** 
1.13.2

**Additional context**
There are usually stone bricks at the start of the round as well, however these are removed from inventory upon picking them up and are a non issue.

**Comment by burturt** [comment]
Fixed in https://github.com/burturt/Monster-Industries/releases/tag/4.0.0-beta.2. Nice eye!
